name: scan_swift
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  camera: ^0.11.1
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  image: ^4.5.2
  http: ^1.3.0
  firebase_core: ^3.11.0
  http_parser: ^4.1.2
  path_provider: ^2.1.5

flutter_icons:
  android: "ic_launcher"
  image_path: "images/scan.png"
  min_sdk_android: 23


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - images/scan.png
     - images/aadhaar.gif
     - images/aadhar_format.png
     - images/sample_13.jpg

