// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2U162JvPGggaFO76PkZV2mXNmei7NZtA',
    appId: '1:80413625270:web:28b310b5affb61d6dfcf17',
    messagingSenderId: '80413625270',
    projectId: 'aadharocr-3cec0',
    authDomain: 'aadharocr-3cec0.firebaseapp.com',
    storageBucket: 'aadharocr-3cec0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDh5ZOo9KDvzNi6YUJ-H1gJ0LpX28zQ8o',
    appId: '1:80413625270:android:48e9dbdad7049f52dfcf17',
    messagingSenderId: '80413625270',
    projectId: 'aadharocr-3cec0',
    storageBucket: 'aadharocr-3cec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabKGXTkYCyUxca61OegjKcg8t110ViC8',
    appId: '1:80413625270:ios:972fc590d5eb2104dfcf17',
    messagingSenderId: '80413625270',
    projectId: 'aadharocr-3cec0',
    storageBucket: 'aadharocr-3cec0.firebasestorage.app',
    iosBundleId: 'com.example.scanSwift',
  );
}
